Отрефакторить task-module
deadmazay1994/chicaga_edu_front pull request #100
Opened 2022-06-09 11:36 UTC by Anodoree

https://trello.com/c/xxmQcdot

2022-06-09 11:37 UTC, Anodoree commented
![](https://github.trello.services/images/mini-trello-icon.png) [Отрефакторить task-module](https://trello.com/c/xxmQcdot/62-%D0%BE%D1%82%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D1%82%D1%8C-task-module)

2022-06-10 07:11 UTC, GizzaProgger requested changes

2022-06-10 07:11 UTC, GizzaProgger commented on src/components/LessonComponents/TabsComponent/TabComponent.vue
> +  height: 100%
Нельзя без необходимости задавать height
Ты таким образом создаешь неявное повоедение компонента. Нужно его задавать во вне
Хоть это свойство является как бы внутренним, но оно сильно ораничивает компонент и делает его менее перееиспользуемым

2022-06-10 07:31 UTC, Anodoree commented on src/components/LessonComponents/TabsComponent/TabComponent.vue
> +  height: 100%
![2022-06-10_10-20-20](https://user-images.githubusercontent.com/82028920/173012490-9a194526-e0f7-4991-ac24-b770d6e89ffc.png)
![2022-06-10_10-19-38 (2)](https://user-images.githubusercontent.com/82028920/173012495-b545ac2b-3da3-41b6-aa2a-6c8d69da9f1a.png)
коротко о том, что изображено: не будет height 100% - не будет прокрутки внутри.


![2022-06-10_10-27-41](https://user-images.githubusercontent.com/82028920/173013469-2813ab54-b628-4924-a1c4-bc269adcd329.png)
tab-component - он как li у ol/ul. - он неотделим от него. И когда они являются табами - они занимают всё пространство. Так почему они не должны быть 100% по высоте когда они табы?

2022-06-10 07:38 UTC, GizzaProgger commented on src/components/LessonComponents/TabsComponent/TabComponent.vue
> +  height: 100%
Тоже верно
Да, пусть так и будет

2022-06-10 08:16 UTC, merged