Вывести видео на всю ширину если заданий нет в уроке
deadmazay1994/chicaga_edu_front pull request #258
Opened 2022-08-23 15:40 UTC by EVGEN002

2022-08-23 15:41 UTC, EVGEN002 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вывести видео на всю ширину если заданий нет в уроке](https://trello.com/c/oXFLsbYX/404-%D0%B2%D1%8B%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-%D0%BD%D0%B0-%D0%B2%D1%81%D1%8E-%D1%88%D0%B8%D1%80%D0%B8%D0%BD%D1%83-%D0%B5%D1%81%D0%BB%D0%B8-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B9-%D0%BD%D0%B5%D1%82-%D0%B2-%D1%83%D1%80%D0%BE%D0%BA%D0%B5)

2022-08-24 09:21 UTC, GizzaProgger commented on src/components/LessonComponents/EduPanel.vue
> +      console.log("TEST lessonData:", lessonData);
Логов не должно быть в пулле

2022-08-24 09:25 UTC, GizzaProgger requested changes

2022-08-24 09:25 UTC, GizzaProgger commented on src/components/LessonComponents/EduPanel.vue
> +      if (this.lesson.lesson.length == 0) this.$emit("tasksIsEmpty");
Зачем тут js использовать. Если нет контента, то не рендери вообще компонент. А в его родителе поправить верстку таким образом, чтобы  леементы занимали все свободное пространство
Свойство у css если что есть <selector>:empty
Работает когда в блоке нет контента.
Может быть пригодится. Если что попроси помощи у Андрея

2022-08-25 09:02 UTC, merged