Сделай функциональной страницу оформления заказа
deadmazay1994/chicaga_edu_front pull request #86
Opened 2022-06-06 13:32 UTC by EVGEN002

Директива работает, но пока не придумал как связать её с компонентом. В stand есть пример

2022-06-08 14:48 UTC, GizzaProgger commented
Сделал мерж из дева

Какой-то баг со слайдером на главной в магазине

2022-06-08 15:59 UTC, GizzaProgger requested changes

2022-06-08 15:59 UTC, GizzaProgger commented on src/main.js
> +Vue.directive("mask", {
Не вижу, чтобы ты использовал директиву
Лучше не писать свой,а использовать уже готовый

2022-06-22 10:46 UTC, EVGEN002 commented
> Сделал мерж из дева

> Какой-то баг со слайдером на главной в магазине
 

Проблема со слайдером решена

2022-06-23 17:40 UTC, merged