Рефакторинг Header
deadmazay1994/chicaga_edu_front pull request #89
Opened 2022-06-07 20:40 UTC by Anodoree

https://trello.com/c/I2Jt9AWu

2022-06-07 20:40 UTC, Anodoree commented
![](https://github.trello.services/images/mini-trello-icon.png) [Рефакторинг Header](https://trello.com/c/I2Jt9AWu/50-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-header)

2022-06-08 06:38 UTC, GizzaProgger requested changes

2022-06-08 06:38 UTC, GizzaProgger commented on src/components/Base/Header.vue
> +  &__avatar img
А тут почему через пробел, а не по классу

2022-06-08 06:38 UTC, GizzaProgger commented on src/components/Base/Header.vue
>            </div>
А где у хедера бордер снизу
По дизайну же бордер должен быть

2022-06-08 06:45 UTC, Anodoree commented on src/components/Base/Header.vue
>            </div>
Он у оболочки хедера у шаблона, на сколько я помню. Это для того, чтобы при манипуляции именно с блоком хедера лишнего не глючило, как это было.
На самом деле путей решений есть много, но эту полоску решил применить к тому месту, где хедер будет вставляться.

2022-06-08 16:11 UTC, merged