Добавил параметр - цвет в хлебные крошки
deadmazay1994/chicaga_edu_front pull request #94
Opened 2022-06-08 11:14 UTC by EVGEN002

Также изменил логику в компоненте

2022-06-08 11:15 UTC, EVGEN002 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить параметр - цвет в хлебные крошки](https://trello.com/c/KuIHQ7ku/46-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80-%D1%86%D0%B2%D0%B5%D1%82-%D0%B2-%D1%85%D0%BB%D0%B5%D0%B1%D0%BD%D1%8B%D0%B5-%D0%BA%D1%80%D0%BE%D1%88%D0%BA%D0%B8)

2022-06-08 16:14 UTC, GizzaProgger requested changes

2022-06-08 16:14 UTC, GizzaProgger commented on src/components/Base/BreadcrumbsComponent.vue
> +      console.log("this.$route.matched:", this.$route.matched);
Даже разбираться не хочется в коде
Отректори его как-то. Ну слишком запутан

Да и у меня не работают крошки вот тут
/#/lesson/34f044b0d82061e8cf8e9a18c6e020d7/

2022-06-10 07:02 UTC, GizzaProgger requested changes

2022-06-10 07:02 UTC, GizzaProgger commented on src/components/Base/BreadcrumbsComponent.vue
> +        :style="{ color: breadcrumb.breadcrumb.color }"
Слишком сложная структура у breadcrumb
Зачем там объект в объекте. Достаточно того, чтобы breadcrumb имел плоскую структуру. Сделать ее сможешь?

2022-06-22 09:02 UTC, merged